name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: '3.1.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --no-incremental
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack
    - name: Nuget publish
      run: dotnet nuget push ./Src/bin/Debug/*.nupkg --api-key ${{ secrets.NUGET_PUSH_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
